// include/environments/pancake_environment.h

#pragma once

#include <array>
#include <cstdint>
#include <cstdlib>  // std::abs
#include <vector>
#include "node.h"
#include "fnv_hash.h"
#include "phmap.h"

// N-pancake sorting problem with unit edge costs.
// A successor is generated by flipping the top k pancakes (2 <= k <= N).
// Heuristic is the gap heuristic: counts adjacent pairs that differ by more than 1.
class PancakeEnvironment {

public:

  static constexpr size_t N = 48;
  using T = std::array<uint8_t, N>;

  PancakeEnvironment(uint32_t seed = 42, uint32_t capacity = 1e7);

  void reset_search() { pool_.prepare_for_search(); }

  void get_successors(uint32_t u_id, std::vector<uint32_t>& neighbors);

  inline uint32_t get_heuristic(uint32_t id) const {
    if (h_costs_[id] != INF_COST) return h_costs_[id];
    const T& state = node_states_[id];
    uint32_t gaps = 0;
    for (size_t i = 0; i < state.size() - 1; i++) {
      if (std::abs((int)state[i] - (int)state[i+1]) > 1) gaps++;
    }
    // Plate boundary: goal bottom is N-1, treat the plate edge as an implicit neighbour.
    if (state[N-1] != (uint8_t)(N - 1)) gaps++;
    h_costs_[id] = gaps;
    return gaps;
  }

  bool is_goal(uint32_t id) const { return id == goal_id_; }

  uint32_t get_start_node();

  inline uint32_t get_edge_cost(uint32_t u, uint32_t v) const { return 1; }

  NodePool& get_pool() { return pool_; }
  const NodePool& get_pool() const { return pool_; }

  uint32_t generate_start_node();
  const T& get_state(uint32_t id) const { return node_states_[id]; }
  uint32_t get_or_create_id(const T& state);

private:

  uint32_t capacity_;
  NodePool pool_;

  std::vector<T> node_states_;
  mutable std::vector<uint32_t> h_costs_;   // cached heuristic values; INF_COST = not yet computed
  phmap::flat_hash_map<T, uint32_t, FnvHash> lookup_table_;

  T start_state_;
  T goal_state_;
  uint32_t goal_id_;
  uint32_t seed_;

};
